=== mkurzydlowski/ewp-specs-api-courses2/endpoints/get-response.xsd
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:ewp="https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd"
    xmlns:trm="https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/tree/stable-v2"
    elementFormDefault="qualified"

    targetNamespace="https://github.com/erasmus-without-paper/ewp-specs-api-courses/tree/stable-v1"
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-courses/tree/stable-v1"
>
    <xs:import
        schemaLocation="https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-architecture/stable-v1/common-types.xsd"
        namespace="https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd"
    />

    <xs:import
        schemaLocation="https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-types-academic-term/stable-v2/schema.xsd"
        namespace="https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/tree/stable-v2"
    />

    <xs:annotation>
        <xs:documentation>
            This schema is a part of the Erasmus Without Paper project. Before you start
            using it, make sure you have read the general rules described here:

            https://developers.erasmuswithoutpaper.eu/
        </xs:documentation>
    </xs:annotation>

    <xs:element name="courses-response">
        <xs:annotation>
            <xs:documentation>
                This describes the format of the response returned by the EWP Courses API.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="course" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            This represents a single course. Servers will produce one such element for
                            each of the `course_id` values passed in the Courses API call.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="ewp:AsciiPrintableIdentifier">
                                <xs:annotation>
                                    <xs:documentation>
                                        Unique identifier of this course. It SHOULD NOT be displayed to the user (use
                                        `code` for that).

                                        Server implementers MUST use immutable surrogate keys for their work with EWP
                                        (we recommend choosing UUID surrogate keys). You can read about this here:
                                        https://github.com/erasmus-without-paper/ewp-specs-architecture#ids
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="title" type="ewp:StringWithOptionalLang" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                                        The name(s) of the course.

                                        Note for server implementers:

                                        You MUST provide at least one name, preferably in English. If your node does
                                        not have a name (or cannot have a name), then you should attempt to generate
                                        one, for example, based on its ID and type. As a last resort, use an empty
                                        string here.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="code" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>
                                        Since course IDs should be surrogate identifiers (and, as such, should not be
                                        displayed to the user), we allow additional "human-readable" unique codes (aka
                                        "natural identifiers") to be provided here. These codes MAY be displayed to the
                                        user along the course title, but they are *not used* to identify entities in EWP
                                        network.

                                        Related links:
                                        https://github.com/erasmus-without-paper/ewp-specs-architecture#ids
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="description" type="ewp:MultilineStringWithOptionalLang" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                                        Description of the course with optional language code.

                                        This field MAY be displayed to the user, but it might be better to refer the
                                        user to a more "user-friendly" web page instead (the one given in the `url`
                                        element above). The primary purpose of the description field is to provide
                                        keywords for full-text searching. Server implementers are encouraged to provide
                                        as many types of information as they like here, but this information should
                                        still be divided in meaningful paragraphs and be human-readable.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="learningOutcomes" type="ewp:MultilineStringWithOptionalLang" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                                        Learning outcomes with optional language code.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="academic-term-id" type="trm:TermId">
                                <xs:annotation>
                                    <xs:documentation>
                                        Describes the academic term in which the course takes place.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="ects" type="xs:decimal">
                                <xs:annotation>
                                    <xs:documentation>
                                        This number of ECTS credits which the student should achieve by completing
                                        this course.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="languageOfInstruction" type="xs:language">
                                <xs:annotation>
                                    <xs:documentation>
                                        An BCP 47 code of the
                                        language which has been used as the primary language of teaching during the
                                        classes. E.g. "pl" if the course is instructed/conducted in Polish.

                                        A note for server implementers: This MUST be a single language. If multiple
                                        languages were used, attempt to select the primary one.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="iscedCode" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>
                                        The ISCED-F code of the course.

                                        ISCED-F codes define fields of education and training at the secondary,
                                        post-secondary and tertiary levels of education. Details:
                                        https://www.uis.unesco.org/Education/Documents/isced-fields-of-education-training-2013.pdf
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="subjectArea" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>
                                        The Erasmus subject area code of the course.

                                        It is named "subjectArea" for consistency with older ELMO-based formats.
                                        https://github.com/erasmus-without-paper/ewp-specs-api-courses/issues/6
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="otherCategorization" type="xs:string" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>
                                        Any other term used internally to describe the field of education of the course.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="unavailableForIncomingMobility" type="xs:boolean" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>
                                        Return true when the course is not available for incoming exchange students to enroll.

                                        Unless explicitly stated, client implementations should assume this as false.
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="url" type="ewp:HTTPWithOptionalLang" minOccurs="0" maxOccurs="unbounded">
                                <xs:annotation>
                                    <xs:documentation>
                                        The URL of the web page with the description of the course.

                                        The xml:lang attribute, if given, SHOULD represent the language of this page.
                                        Multiple URLs can be provided (with different xml:lang values). It is also
                                        perfectly okay to provide a single URL which dynamically detects the viewer's
                                        language preferences (in this case, no xml:lang attribute should be given).
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mkurzydlowski/ewp-specs-api-courses2/endpoints/get-response-example.xml
<courses-response
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-courses/tree/stable-v1"
    xmlns:trm="https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/tree/stable-v2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://github.com/erasmus-without-paper/ewp-specs-api-courses/tree/stable-v1
        get-response.xsd
    "
>
    <course>
        <id>f6d14b1f-f330-4956-8819-e24feb12d519</id>
        <code>COUR01</code>
        <title xml:lang="no">Grunnkurs i matematikk</title>
        <title xml:lang="en">Introductory calculus</title>
        <subjectArea>12345</subjectArea>
        <iscedCode>0541</iscedCode>
        <description xml:lang="no">En eller annen beskrivelse</description>
        <description xml:lang="en">Some description</description>
        <academic-term-id>
            <trm:term-number>1</trm:term-number>
            <trm:total-terms>2</trm:total-terms>
        </academic-term-id>
        <ects>15</ects>
        <languageOfInstruction>en</languageOfInstruction>
    </course>
</courses-response>
